[build]
  functions = "src/functions"
  NODE_ENV = "12"
  publish = "dist"

[dev]
  port = 8080
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "https://lucid-gates-913afd.netlify.com/*"
  to = "https://content.oktadev.dev/:splat"
  status = 301
  force = true

